author: "Tobe O <thosakwe@gmail.com>"
description: "angel_auth strategy for Google OAuth2 login."
homepage: "https://github.com/angel-dart/auth_google"
name: "angel_auth_google"
version: "1.1.0"
dependencies: 
  angel_auth: "^1.1.0-alpha"
  googleapis: "^0.32.0"
  googleapis_auth: "^0.2.3"
  http: "^0.11.3"
dev_dependencies: 
  angel_compress: "^1.0.0"
  angel_diagnostics: "^1.0.0-dev"
  console: "^2.2.4"
  test: "^0.12.15"
environment: 
  sdk: ">=1.19.0"
